language: "en-US"

reviews:
  profile: chill
  collapse_walkthrough: true
  poem: false
  review_status: true
  high_level_summary: true

  auto_review:
    enabled: true
    drafts: false
    base_branches: ["main"]

chat:
  auto_reply: true
